// <auto-generated />
using System;
using FormBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251217110805_RemovedFacultyEntityAndUpdateAcademicEnrollment")]
    partial class RemovedFacultyEntityAndUpdateAcademicEnrollment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormBackend.Models.AcademicEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Faculty")
                        .HasColumnType("int");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentPID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentPID")
                        .IsUnique();

                    b.ToTable("AcademicEnrollments");
                });

            modelBuilder.Entity("FormBackend.Models.AcademicHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Board")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PassedYear")
                        .HasColumnType("date");

                    b.Property<double>("PercentageOrGPA")
                        .HasColumnType("float");

                    b.Property<Guid>("StudentPID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentPID");

                    b.ToTable("AcademicHistories");
                });

            modelBuilder.Entity("FormBackend.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnnualIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Relation")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentPID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentPID");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("FormBackend.Models.Student", b =>
                {
                    b.Property<Guid>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FormBackend.Models.AcademicEnrollment", b =>
                {
                    b.HasOne("FormBackend.Models.Student", "Student")
                        .WithOne("AcademicEnrollment")
                        .HasForeignKey("FormBackend.Models.AcademicEnrollment", "StudentPID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FormBackend.Models.AcademicHistory", b =>
                {
                    b.HasOne("FormBackend.Models.Student", "Student")
                        .WithMany("AcademicHistories")
                        .HasForeignKey("StudentPID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FormBackend.Models.Parent", b =>
                {
                    b.HasOne("FormBackend.Models.Student", "Student")
                        .WithMany("Parents")
                        .HasForeignKey("StudentPID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FormBackend.Models.Student", b =>
                {
                    b.OwnsMany("FormBackend.Models.Achievement", "Achievements", b1 =>
                        {
                            b1.Property<Guid>("StudentPID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime?>("DateOfAchievement")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentPID", "Id");

                            b1.ToTable("Achievements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StudentPID");
                        });

                    b.OwnsMany("FormBackend.Models.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("StudentPID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Municipality")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<string>("Ward")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentPID", "Id");

                            b1.ToTable("Addresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StudentPID");
                        });

                    b.OwnsOne("FormBackend.Models.Citizenship", "Citizenship", b1 =>
                        {
                            b1.Property<Guid>("StudentPID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CitizenshipNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CountryOfIssuance")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("DateOfIssuance")
                                .HasColumnType("datetime2");

                            b1.Property<string>("PlaceOfIssuance")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentPID");

                            b1.ToTable("Citizenships", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StudentPID");
                        });

                    b.OwnsOne("FormBackend.Models.Disability", "Disability", b1 =>
                        {
                            b1.Property<Guid>("StudentPID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double?>("DisabilityPercentage")
                                .HasColumnType("float");

                            b1.Property<string>("DisabilityType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentPID");

                            b1.ToTable("Disabilities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StudentPID");
                        });

                    b.OwnsMany("FormBackend.Models.Hobby", "Hobbies", b1 =>
                        {
                            b1.Property<Guid>("StudentPID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentPID", "Id");

                            b1.ToTable("Hobbies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StudentPID");
                        });

                    b.OwnsOne("FormBackend.Models.Scholarship", "Scholarship", b1 =>
                        {
                            b1.Property<Guid>("StudentPID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ScholarshipName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("StudentPID");

                            b1.ToTable("Scholarships", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StudentPID");
                        });

                    b.OwnsOne("FormBackend.Models.SecondaryInfos", "SecondaryInfos", b1 =>
                        {
                            b1.Property<Guid>("StudentPID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AcademicCertificatePaths")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AlternateEmail")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AlternateMobile")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentPID");

                            b1.ToTable("SecondaryInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StudentPID");
                        });

                    b.Navigation("Achievements");

                    b.Navigation("Addresses");

                    b.Navigation("Citizenship");

                    b.Navigation("Disability");

                    b.Navigation("Hobbies");

                    b.Navigation("Scholarship");

                    b.Navigation("SecondaryInfos");
                });

            modelBuilder.Entity("FormBackend.Models.Student", b =>
                {
                    b.Navigation("AcademicEnrollment");

                    b.Navigation("AcademicHistories");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
